#logging.level.org.springframework.boot.autoconfigure: ERROR
logging:
  file: server.log
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.zxy: DEBUG

#spring:
#    profiles:
#        active: product
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/zxy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#        username: root
#        password: root
#    jpa:
#        hibernate:
#            ddl-auto: update
#        show-sql: true
#    jackson:
#        date-format: yyyy-MM-dd HH:mm:ss
#        time-zone: UTC